services:
  virtuoso:
    build:
      context: .
      dockerfile: Dockerfile.virtuoso
    ports:
      - "8890:8890"
      - "1111:1111"
    volumes:
      - shared-ld:/app/ld
      - shared-rdf:/app/work/rdf-output/temp
      - virtuoso-db:/opt/virtuoso-opensource/var/lib/virtuoso/db
    environment:
      VIRTUOSO_DBA_PASSWORD: dba

  cmd2rdf:
    build:
      context: .
      dockerfile: Dockerfile.cmd2rdf
    ports:
      - "8080:8080"
    volumes:
      - shared-ld:/app/ld
      - shared-rdf:/app/work/rdf-output/temp

volumes:
  virtuoso-db:
  shared-ld:
  shared-rdf:
