FROM ubuntu:latest

ENV CMD2RDF_SRC=git
ENV CMD2RDF_HOST=http://localhost:8080
ENV CMD2RDF_HOME=/app
ENV STORE_HOST=http://graphdb:7200

RUN apt-get -y update && \
    apt-get -y install --no-install-recommends \
        openjdk-8-jdk \
        maven \
        curl \
        git \
        bzip2 && \
    rm -rf /var/lib/apt/lists/* /tmp/*

WORKDIR /app

RUN mkdir -p \
    /app/src \
    /app/data \
    /app/work/harvester \
    /app/work/profiles-cache \
    /app/work/rdf-output/temp \
    /app/ld \
    /app/vlo \
    /app/logs/cmd2rdf

COPY ld/* /app/ld/
RUN chmod 755 /app/ld/*.sh && \
    mv /app/ld/meertens-VLO-orgs.rdf /app/work/harvester/meertens-VLO-orgs.rdf

COPY get-cmd2rdf.sh /app/get-cmd2rdf.sh
RUN chmod +x /app/get-cmd2rdf.sh

WORKDIR /app/src
RUN /app/get-cmd2rdf.sh && \
    sed -i "s|/app|$CMD2RDF_HOME|g"                  /app/src/CMD2RDF/batch/src/main/resources/cmd2rdf.xml && \
    sed -i "s|Put here a strong password!|${PASS}|g" /app/src/CMD2RDF/batch/src/main/resources/cmd2rdf.xml && \
    sed -i "s|http://localhost:8890|$STORE_HOST|g"   /app/src/CMD2RDF/batch/src/main/resources/cmd2rdf.xml && \
    sed -i "s|http://localhost:8080|$CMD2RDF_HOST|g" /app/src/CMD2RDF/batch/src/main/resources/cmd2rdf.xml && \
    rm /app/get-cmd2rdf.sh

WORKDIR /app/src/CMD2RDF
RUN mvn clean install -q --no-transfer-progress && \
    rm -rf /root/.m2/repository

COPY cmd2rdf-cron.sh cmd2rdf-run.sh /app/
RUN chmod 755 /app/*.sh

EXPOSE 8080

WORKDIR /app