services:
  graphdb:
    build:
      context: .
      dockerfile: Dockerfile.graphdb
    ports:
      - "7200:7200"
    volumes:
      - graphdb-repositories:/opt/graphdb/dist/data/repositories

  cmd2rdf:
    build:
      context: .
      dockerfile: Dockerfile.cmd2rdf
    ports:
      - "8080:8080"
    volumes:
      - app-data:/app/data

volumes:
  graphdb-repositories:
  app-data:
