services:
  virtuoso:
    build:
      context: .
      dockerfile: Dockerfile.virtuoso
    ports:
      - "8890:8890"
      - "1111:1111"
    volumes:
      - virtuoso_data:/opt/virtuoso-opensource/var/lib/virtuoso/db

  cmd2rdf:
    build:
      context: .
      dockerfile: Dockerfile.cmd2rdf
    ports:
      - "8080:8080"

volumes:
  virtuoso_data:
