# Keep this around, just in case we need a fallback
FROM openlink/virtuoso-opensource-7

RUN apt-get -y update
RUN apt-get -y clean
RUN apt-get -y install supervisor

RUN mkdir -p /opt/virtuoso-opensource/var/lib/virtuoso/db
ADD virtuoso.ini /opt/virtuoso-opensource/var/lib/virtuoso/db/virtuoso.ini

ADD start-virtuoso.sh /start-virtuoso.sh
ADD supervisord-virtuoso.conf /etc/supervisor/conf.d/supervisord-virtuoso.conf

ADD run.sh /run.sh
RUN chmod 755 /*.sh

EXPOSE 1111
EXPOSE 8890

CMD ["/run.sh"]