events { }

http {
     error_log /dev/stderr debug;

     log_format proxy-debug '$remote_addr - $remote_user [$time_local] '
                            '"$request" $status $body_bytes_sent '
                            '"$http_referer" "$http_user_agent" '
                            'Accept="$http_accept" '
                            'format="$arg_format" '
                            'upstream="$upstream_addr" '
                            'resptime=$request_time';

    access_log /var/log/nginx/access.log proxy-debug;

    # Map query param "format" to the right Accept header
    map $arg_format $accept_override {
        default                                    "application/sparql-results+xml";
        "application/sparql-results+xml"           "application/sparql-results+xml";
        "application/atom+xml"                     "application/sparql-results+xml";
    }

    server {
        listen 8080;

        location / {
            proxy_pass http://graphdb:7200;
            proxy_http_version 1.1;

            proxy_buffering on;
            # No chunking please
            chunked_transfer_encoding off;
            # Erase accept encoding
            proxy_set_header Accept-Encoding "";
            # Set Accept header according to map
            proxy_set_header Accept $accept_override;
            # Wrap named graph IRI in < ... >
            proxy_set_header X-Context "%3C$arg_context%3E";

            # Rewrite 'old' sparql paths to correct GraphDB repository
            rewrite ^/sparql(.*)$ /repositories/REPO_ID$1 break;
        }
    }
}