[supervisord]
nodaemon=true
user=root

[program:graphdb]
command=/start-graphdb.sh
numprocs=1
autostart=true
autorestart=true

[program:init-repo]
command=/graphdb-init.sh
autostart=true
autorestart=false